name: CI - Build & Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      user-service: ${{ steps.filter.outputs.user-service }}
      order-service: ${{ steps.filter.outputs.order-service }}
      book-service: ${{ steps.filter.outputs.book-service }}

    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            user-service:
              - 'user-service/**'
            order-service:
              - 'order-service/**'
            book-service:
              - 'book-service/**'

  build:
    needs: detect-changes
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [ "user-service", "order-service", "book-service" ]

    steps:
      - uses: actions/checkout@v3

      # Read dynamic output using $GITHUB_OUTPUT
      - name: Read changed flag
        id: changed
        run: |
          echo "updated=${{ needs.detect-changes.outputs[matrix.service] }}" >> $GITHUB_OUTPUT

      # Skip using step output (matrix works here)
      - name: Skip if no changes
        if: ${{ steps.changed.outputs.updated != 'true' }}
        run: |
          echo "No changes in '${{ matrix.service }}' â†’ skipping"
          exit 0

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }} ./${{ matrix.service }}

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }}
