name: PR - Build Changed Microservices

on:
  pull_request:
    branches:
      - main

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      user-service: ${{ steps.filter.outputs.user-service }}
      order-service: ${{ steps.filter.outputs.order-service }}
      book-service: ${{ steps.filter.outputs.book-service }}

    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # REQUIRED so we can diff base ←→ head

      - name: Detect Changed Folders
        uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.event.pull_request.head.sha }}
          filters: |
            user-service:
              - "user-service/**"
            order-service:
              - "order-service/**"
            book-service:
              - "book-service/**"

  build-user:
    needs: detect
    if: ${{ needs.detect.outputs['user-service'] == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/user-service:${{ github.sha }} ./user-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/user-service:${{ github.sha }}

  build-order:
    needs: detect
    if: ${{ needs.detect.outputs['order-service'] == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/order-service:${{ github.sha }} ./order-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/order-service:${{ github.sha }}

  build-book:
    needs: detect
    if: ${{ needs.detect.outputs['book-service'] == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/book-service:${{ github.sha }} ./book-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/book-service:${{ github.sha }}
