name: CI - Build & Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [ "user-service", "order-service", "book-service" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Get changed files
      - name: Get changed files
        id: changes
        run: |
          echo "changed=$(git diff --name-only HEAD~1 HEAD | tr '\n' ' ')" >> $GITHUB_OUTPUT
      # Skip this job if this service didn't change
      - name: Skip if no changes for this service
        if: ${{ !contains(steps.changes.outputs.changed, matrix.service) }}
        run: |
          echo "No changes in '${{ matrix.service }}' â†’ skipping."
          exit 0
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }} ./${{ matrix.service }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }} \
                     ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
